# Generated by Django 3.0.10 on 2020-11-03 09:07

import app.core.db.fields
import app.utils.storages
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('type', app.core.db.fields.PositiveTinyIntegerField(null=True)),
                ('for_event_flg', models.IntegerField(null=True)),
                ('image', models.ImageField(storage=app.utils.storages.MediaRootS3Boto3Storage, upload_to='')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('outline', models.CharField(blank=True, max_length=500, null=True)),
                ('publication_start_date', models.DateField(blank=True, null=True)),
                ('publication_end_date', models.DateField(blank=True, null=True)),
                ('status', app.core.db.fields.PositiveTinyIntegerField(null=True)),
                ('pv_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'special_feature',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('kigyo_name', models.CharField(max_length=200)),
                ('kigyo_kana', models.CharField(max_length=200)),
                ('main_mail', models.EmailField(max_length=60)),
                ('main_tel', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('adopt_status', app.core.db.fields.PositiveTinyIntegerField(default=0)),
                ('notify_mail1', models.EmailField(blank=True, max_length=60, null=True)),
                ('notify_mail2', models.EmailField(blank=True, max_length=60, null=True)),
                ('notify_mail3', models.EmailField(blank=True, max_length=60, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company')),
            ],
            options={
                'db_table': 'company_profile',
            },
        ),
    ]
