# Generated by Django 3.0.10 on 2020-11-03 09:07

import app.core.db.fields
import app.utils.storages
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True, max_length=3000, null=True)),
                ('file', models.FileField(blank=True, null=True, storage=app.utils.storages.MediaRootS3Boto3Storage, upload_to='')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_master_company', app.core.db.fields.PositiveTinyIntegerField(null=True)),
                ('is_master_student', app.core.db.fields.PositiveTinyIntegerField(null=True)),
                ('is_company', app.core.db.fields.PositiveTinyIntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('body', models.TextField(blank=True, max_length=3000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanyProfile')),
            ],
            options={
                'db_table': 'message_template',
            },
        ),
        migrations.CreateModel(
            name='AutoReplyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', app.core.db.fields.PositiveTinyIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanyProfile')),
                ('type_auto_reply_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.TypeAutoReplyMessage')),
            ],
            options={
                'db_table': 'auto_reply_message',
            },
        ),
    ]
