# Generated by Django 3.0.10 on 2020-11-06 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0002_auto_20201105_1902'),
        ('admin_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmagazine',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.CompanyProfile'),
        ),
    ]
