# Generated by Django 3.0.10 on 2020-11-09 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_profile', '0002_auto_20201106_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_profile.StaffAuth'),
        ),
    ]
