# Generated by Django 3.0.10 on 2020-11-03 09:07

import app.core.db.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTypeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'company_type_category',
            },
        ),
        migrations.CreateModel(
            name='JobTypeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'job_type_category',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('val', models.IntegerField()),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='SchoolInfoMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', app.core.db.fields.PositiveTinyIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0)),
                ('school_division', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('kana', models.CharField(blank=True, max_length=256, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('bunri', models.CharField(blank=True, max_length=10, null=True)),
                ('bunri_option', models.CharField(blank=True, max_length=100, null=True)),
                ('department_code', models.IntegerField(null=True)),
                ('campus', models.CharField(blank=True, max_length=100, null=True)),
                ('prefecture', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('local_code', models.CharField(blank=True, max_length=10, null=True)),
                ('establishment_division', models.CharField(blank=True, max_length=45, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('k_code', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('join_research', models.CharField(blank=True, max_length=200, null=True)),
                ('belong_university', models.CharField(blank=True, max_length=200, null=True)),
                ('belong_college', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'school_info_master',
            },
        ),
        migrations.CreateModel(
            name='TypeAutoReplyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type_auto_reply_message',
            },
        ),
        migrations.CreateModel(
            name='WorkPlaceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'work_place_category',
            },
        ),
        migrations.CreateModel(
            name='WorkPlaceMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.WorkPlaceCategory')),
            ],
            options={
                'db_table': 'work_place_master',
            },
        ),
        migrations.CreateModel(
            name='JobTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('order_by', models.IntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.JobTypeCategory')),
            ],
            options={
                'db_table': 'job_type_master',
            },
        ),
        migrations.CreateModel(
            name='CompanyTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.CompanyTypeCategory')),
            ],
            options={
                'db_table': 'company_type_master',
            },
        ),
    ]
