# Generated by Django 3.0.10 on 2020-11-03 09:07

import app.core.db.fields
import app.utils.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', app.core.db.fields.PositiveTinyIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0)),
                ('target_year', models.IntegerField(null=True)),
                ('class_division', models.CharField(blank=True, max_length=100, null=True)),
                ('event_name', models.TextField()),
                ('pdf_name', models.TextField()),
                ('image', models.ImageField(storage=app.utils.storages.MediaRootS3Boto3Storage, upload_to='')),
                ('date', models.DateField()),
                ('sub_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('sub_start_time', models.TimeField(blank=True, null=True)),
                ('sub_end_time', models.TimeField(blank=True, null=True)),
                ('place', models.TextField()),
                ('place_google', models.TextField()),
                ('sub_place', models.TextField(blank=True, null=True)),
                ('sub_place_google', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('stamp', models.CharField(max_length=10)),
                ('reserve_start', models.DateField()),
                ('reserve_end', models.DateField()),
                ('release_url', models.TextField()),
                ('release_date', models.DateField()),
                ('publication_end', models.DateField()),
                ('is_top_display', app.core.db.fields.PositiveTinyIntegerField(default=0)),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
