# Generated by Django 3.0.10 on 2020-11-04 04:11

import app.core.db.fields
import app.utils.storages
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequestWorkplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
                ('work_place_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.WorkPlaceMaster')),
            ],
            options={
                'db_table': 'student_request_workplace',
            },
        ),
        migrations.CreateModel(
            name='StudentRequestJobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.JobTypeMaster')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
            options={
                'db_table': 'student_request_job_type',
            },
        ),
        migrations.CreateModel(
            name='StudentRequestFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
            options={
                'db_table': 'student_request_feature',
            },
        ),
        migrations.CreateModel(
            name='StudentRequestCompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.CompanyTypeMaster')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
            options={
                'db_table': 'student_request_company_type',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('policy', app.core.db.fields.PositiveTinyIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name_kana', models.CharField(max_length=50)),
                ('last_name_kana', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('image', models.ImageField(default='.s3.amazonaws.com/uploads/avatars/defaul-avt.png', storage=app.utils.storages.MediaRootS3Boto3Storage, upload_to='')),
                ('bunri', models.CharField(max_length=5)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('school_division', models.CharField(max_length=10)),
                ('school_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('school_prefecture', models.CharField(blank=True, max_length=300, null=True)),
                ('club_activities', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField()),
                ('graduation_date', models.DateTimeField(blank=True, null=True)),
                ('after_graduation_service', app.core.db.fields.PositiveTinyIntegerField(default=1)),
                ('renewal_date_student', models.DateTimeField(blank=True, null=True)),
                ('renewal_date_master', models.DateTimeField(blank=True, null=True)),
                ('closed', models.DateTimeField()),
                ('tel', models.CharField(max_length=15)),
                ('tel_ng', models.IntegerField(default=0)),
                ('note', models.TextField(max_length=500)),
                ('contact_postal_code', models.CharField(blank=True, max_length=10)),
                ('contact_prefecture', models.CharField(blank=True, max_length=45)),
                ('contact_city', models.CharField(blank=True, max_length=100)),
                ('contact_town', models.CharField(blank=True, max_length=100)),
                ('contact_section', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('prefecture', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('department_division', models.CharField(max_length=100)),
                ('posting', models.IntegerField(default=1)),
                ('accept_mail_flg', app.core.db.fields.PositiveTinyIntegerField(default=1)),
                ('accept_dm_flg', app.core.db.fields.PositiveTinyIntegerField(default=1)),
                ('accept_tel_flg', models.IntegerField(blank=True, null=True)),
                ('admin_updated', models.DateTimeField(blank=True, null=True)),
                ('student_updated', models.DateTimeField(blank=True, null=True)),
                ('status', app.core.db.fields.PositiveTinyIntegerField(default=1)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_student_profile', to='master_data.Media')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
            options={
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='DuplicateStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.StudentProfile')),
            ],
            options={
                'db_table': 'duplicate_student',
            },
        ),
    ]
