# Generated by Django 3.0.10 on 2020-11-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrequestjobtype',
            old_name='job_type_master_id',
            new_name='job_type_master',
        ),
        migrations.RenameField(
            model_name='studentrequestworkplace',
            old_name='work_place_master_id',
            new_name='work_place_master',
        ),
    ]
