#!/bin/bash

BASE_DIR=..

# set environment variables
# https://stackoverflow.com/a/45971167/13505878
set -a
. ${BASE_DIR}/.envs/.local/.aws
set +a

# Push static to AWS S3
# staticfiles generated by whitenoise # setup in settings.base
# with whitenoise, if staticfile changed, static filename will be changed
# therefore client don't need clear browser's cache to get new version of staticfiles
docker-compose -f local.yml run django \
    python3 manage.py collectstatic --no-input --settings=${BASE_DIR}/config/settings.local

# Sync to cloundfront
Caller_Reference="Invalidation all `date '+%FT%T'`"
aws cloudfront create-invalidation --distribution-id ${AWS_CF_DEV} --invalidation-batch "Paths={Quantity=1,Items=[/*]},CallerReference=${Caller_Reference}" --profile ${AWS_PROFILE}
