# Generated by Django 3.0.10 on 2020-11-03 09:07

import app.core.db.fields
import app.utils.storages
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuscript', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=app.utils.storages.MediaRootS3Boto3Storage, upload_to='')),
                ('publication_start_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('needs', models.TextField(blank=True, null=True)),
                ('outline', models.TextField(blank=True, null=True)),
                ('free_title_1', models.TextField(blank=True, null=True)),
                ('free_content_1', models.TextField(blank=True, null=True)),
                ('free_title_2', models.TextField(blank=True, null=True)),
                ('free_content_2', models.TextField(blank=True, null=True)),
                ('number_of_date', models.IntegerField(null=True)),
                ('manuscript', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manuscript.Manuscript')),
            ],
            options={
                'db_table': 'orientation',
            },
        ),
        migrations.CreateModel(
            name='ReservedOrientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('datetime_no', app.core.db.fields.PositiveTinyIntegerField(null=True)),
                ('status', models.SmallIntegerField(null=True)),
                ('number_of_day', models.IntegerField(null=True)),
                ('manuscript_student_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manuscript.ManuscriptStudentRelation')),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientation.Orientation')),
            ],
            options={
                'db_table': 'reserved_orientation',
            },
        ),
        migrations.CreateModel(
            name='OrientationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reserve_start_date', models.DateField(blank=True, null=True)),
                ('reserve_end_date', models.DateField(blank=True, null=True)),
                ('map_info', models.CharField(blank=True, max_length=45, null=True)),
                ('place', models.CharField(blank=True, max_length=45, null=True)),
                ('is_address', app.core.db.fields.PositiveTinyIntegerField(default=0)),
                ('is_accept_reservation', app.core.db.fields.PositiveTinyIntegerField(default=0)),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientation.Orientation')),
            ],
            options={
                'db_table': 'orientation_plan',
            },
        ),
    ]
